### ISSUE TITLE
nativate/prebuilt/linux64下面的文件已经移动到/usr/lib64了，但是执行register.py,结果还是空

### ISSUE THREAD

**Issue by blakefan** [coder-fly/douyin_device_register#8]
`Traceback (most recent call last):
  File "/home/douyin_device_register/register.py", line 58, in <module>
    hex_str = re.search(r'hex=([\s\S]*?)\nsize',stdout.decode()).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
`

**Comment by mrqaidi** [comment]
same issue

**Comment by coder-fly** [comment]
刚刚测试了一下，使用docker运行的一个全新的环境可以得到结果
`docker run -it -v /your_code_path/douyin_device_register:/app --name douyin --rm korekontrol/ubuntu-java-python3 python3 /app/register.py`
